# Analys local dataset with pandas

In [29]:
import pandas as pd
import random
from collections import defaultdict
from pathlib import Path
from tqdm.auto import tqdm

In [52]:
# === CONFIG ===
data_path = 'dataset/animals'
columns = ["filepath", "type", "filename", "BIO", "class", "pagenr"]
DATA_DIR_train = Path(data_path) / "train"
DATA_DIR_val = Path(data_path) / "val"
DATA_DIR_test = Path(data_path) / "test"
TRAIN_FILE = "train.txt"
VAL_FILE = "val.txt"
TEST_FILE = "test.txt"

def gather_samples(data_dir, extension=".png"):
    """
    Gathers samples from a dataset directory.

    Args:
        data_dir (Path): Path to dataset (train/val/test).
        extension (str): File extension to match (e.g., ".png", ".csv").

    Returns:
        List of tuples: (filepath, type, filename, BIO tag, class label, page number)
    """
    samples = []
    dataset_type = data_dir.name  # train, val, or test

    for class_dir in tqdm(list(data_dir.iterdir()), desc=f"Scanning {dataset_type}"):
        if not class_dir.is_dir():
            continue

        class_label = class_dir.name

        for file_path in class_dir.glob(f"*{extension}"):
            filename = file_path.name
            try:
                page_num = int(filename.split("_pagenr_")[-1].split(".")[0])
            except ValueError:
                continue  # skip malformed filenames

            bio_tag = "BEGIN" if page_num == 0 else "INNER"

            samples.append((
                str(file_path.resolve()),  # filepath
                dataset_type,              # type
                filename,                  # filename
                bio_tag,                   # BIO
                class_label,               # class
                page_num                   # pagenr
            ))

    return samples

# === Set seed
random.seed(42)

### Load dataset

In [53]:
# === Gather samples
extension=".jpg"
train_samples = gather_samples(DATA_DIR_train, extension)
val_samples = gather_samples(DATA_DIR_val, extension)
test_samples = gather_samples(DATA_DIR_test, extension)

# === Create DataFrames
train_df = pd.DataFrame(train_samples, columns=columns)
val_df = pd.DataFrame(val_samples, columns=columns)
test_df = pd.DataFrame(test_samples, columns=columns)

Scanning train:   0%|          | 0/22 [00:00<?, ?it/s]

Scanning val:   0%|          | 0/22 [00:00<?, ?it/s]

Scanning test:   0%|          | 0/22 [00:00<?, ?it/s]

### Dataset information

In [54]:
train_df.head()

Empty DataFrame
Columns: [filepath, type, filename, BIO, class, pagenr]
Index: []

In [55]:
test_df.head()

Empty DataFrame
Columns: [filepath, type, filename, BIO, class, pagenr]
Index: []

In [56]:
val_df.head()

Empty DataFrame
Columns: [filepath, type, filename, BIO, class, pagenr]
Index: []

### Analys types

In [57]:
# Assuming your DataFrame is called df
train_summary = train_df.groupby(['class', 'BIO']).size().unstack(fill_value=0)
train_summary

Empty DataFrame
Columns: []
Index: []

In [58]:
# Assuming your DataFrame is called df
test_df = test_df.groupby(['class', 'BIO']).size().unstack(fill_value=0)
test_df

Empty DataFrame
Columns: []
Index: []

In [59]:
# Assuming your DataFrame is called df
val_df = val_df.groupby(['class', 'BIO']).size().unstack(fill_value=0)
val_df

Empty DataFrame
Columns: []
Index: []